packages:
  - '.'
allowBuilds:
  esbuild: true
  workerd: true
overrides:
  "@swup/parallel-plugin@0.4.0>@swup/plugin": "4.0.0"
  "@swup/route-name-plugin@4.1.0>@swup/plugin": "4.0.0"
  "vite@8.2.2>rolldown": "1.2.4"
  "astro@7.2.10>devalue": "5.9.3"
  "svelte@5.57.0>devalue": "5.9.3"
